#####
# This is the YAML configuration file for webgen used to set configuration options.
#
# The general syntax is:
#
#   configuration.option.name: value
#
# For example, to set a different default language, you would do:
#
#   website.lang: de
#
# Have a look at the documentation of the individual configuration options to see the allowed format
# of the values. Since this is a YAML file, you can easily set configuration options as strings,
# integers, dates, arrays, hashes and more.
#
# The available configuration options can be found on the homepage in the Configuration Option
# Reference at
#
#     http://webgen.rubyforge.org/documentation/reference_configuration.html
#
# Some common use cases are shown below.
#####

sources:
  - [/, Webgen::Source::FileSystem, src]

patterns:
  Page:
    add: [**/*.sass]
  Copy:
    add: [**/*.css, **/*.js, **/*.jpeg, **/*.txt]

default_processing_pipeline:
  Page: rdiscount,fragments
  # TODO: use kramdown, but fix errors
  Template: haml

website.lang: ~
website.url: http://mildred.fr/

contentprocessor.haml:
  format: :html5

common.sitemap.used_kinds:
  - page
  - tags
  - index

sourcehandler.casefold: false

output: ["Webgen::Output::FileSystem", "out"]
# false or else files copied via rsync would be deleted
output.do_deletion: false

default_meta_info:
  Page:
    output_path_style:
      - :parent
      - :basename
      - {ifne: [:lang, ''], then: [., :lang]}
      - {ifnot: :index?	, then: "/index"}
      - :ext
  Template:
    base_url: http://mildred.fr
    site_name: Mildred's Website


extensions:
  PreExec:
    - rsync -a --exclude=.git --exclude='*~' static/. out/
  MailDirSource:
    from: maildir
    to: src/Blog/%Y-%m-%d-%%s.page
