baseURL = "http://mildred.fr/"
title = "Chez Mildred"

DefaultContentLanguage = "fr"

[languages]
  [languages.fr]
    title = "Chez Mildred"
    languageName = "Français"
    weight = 1

    [languages.fr.blackfriday]
      angledQuotes = true

    [[languages.fr.menu.main]]
      identifier = "accueil"
      name       = "Accueil"
      title      = ""
      url        = "/"
      weight     = -130

    [[languages.fr.menu.main]]
      identifier = "home"
      name       = "Home"
      title      = ""
      url        = "/en/"
      weight     = -120

    [[languages.fr.menu.main]]
      identifier = "curriculum-vitae"
      name       = "Curriculum Vitæ"
      title      = ""
      url        = "/curriculum-vitae/"
      weight     = -110

    [[languages.fr.menu.main]]
      identifier = "contact"
      name       = "Contact"
      title      = ""
      url        = "/contact/"
      weight     = -100

  [languages.en]
    title = "Mildred's Website"
    languageName = "English"
    weight = 2

    [languages.en.blackfriday]
      angledQuotes = false

    [[languages.en.menu.main]]
      identifier = "accueil"
      name       = "Accueil"
      title      = ""
      url        = "/"
      weight     = -130

    [[languages.en.menu.main]]
      identifier = "home"
      name       = "Home"
      title      = ""
      url        = "/en/"
      weight     = -120

    [[languages.en.menu.main]]
      identifier = "curriculum-vitae"
      name       = "Curriculum Vitæ"
      title      = ""
      url        = "/curriculum-vitae/"
      weight     = -110

    [[languages.en.menu.main]]
      identifier = "contact"
      name       = "Contact"
      title      = ""
      url        = "/contact/"
      weight     = -100
