#####
# This is the YAML configuration file for webgen used to set configuration options.
#
# The general syntax is:
#
#   configuration.option.name: value
#
# For example, to set a different default language, you would do:
#
#   website.lang: de
#
# Have a look at the documentation of the individual configuration options to see the allowed format
# of the values. Since this is a YAML file, you can easily set configuration options as strings,
# integers, dates, arrays, hashes and more.
#
# The available configuration options can be found on the homepage in the Configuration Option
# Reference at
#
#     http://webgen.rubyforge.org/documentation/reference_configuration.html
#
# Some common use cases are shown below.
#####

sources:
  - [/, Webgen::Source::FileSystem, src]

patterns:
  Page:
    add: [**/*.sass]
  Copy:
    add: [**/*.css, **/*.js, **/*.jpeg, **/*.txt]

default_processing_pipeline:
  Page: rdiscount,fragments
  Template: haml

website.lang: fr
website.url: http://mildred.fr/

sourcehandler.casefold: false
output.do_deletion: true

default_meta_info:
  Page:
    output_path_style: [:parent, :basename, {ifne: [:lang, ''], then: [., :lang]}, {ifnot: :_index, then: "/index"}, :ext]
  Template:
    base_url: http://mildred.fr
    site_name: Mildred's Website


pre_exec:
  - rsync -a --exclude=.git --exclude='*~' static/. out/



###################################
## nanoc ##
###########



# A list of file extensions that nanoc will consider to be textual rather than
# binary. If an item with an extension not in this list is found,  the file
# will be considered as binary.
text_extensions: [ 'css', 'erb', 'haml', 'htm', 'html', 'js', 'less', 'markdown', 'md', 'php', 'rb', 'sass', 'scss', 'txt', 'xhtml', 'xml' ]

# The path to the directory where all generated files will be written to. This
# can be an absolute path starting with a slash, but it can also be path
# relative to the site directory.
output_dir: output

# A list of index filenames, i.e. names of files that will be served by a web
# server when a directory is requested. Usually, index files are named
# “index.hml”, but depending on the web server, this may be something else,
# such as “default.htm”. This list is used by nanoc to generate pretty URLs.
index_filenames: [ 'index.html' ]

# Whether or not to generate a diff of the compiled content when compiling a
# site. The diff will contain the differences between the compiled content
# before and after the last site compilation.
enable_output_diff: false

# The data sources where nanoc loads its data from. This is an array of
# hashes; each array element represents a single data source. By default,
# there is only a single data source that reads data from the “content/” and
# “layout/” directories in the site directory.
data_sources:
  -
    # The type is the identifier of the data source. By default, this will be
    # `filesystem_unified`.
    type: filesystem_unified

    # The path where items should be mounted (comparable to mount points in
    # Unix-like systems). This is “/” by default, meaning that items will have
    # “/” prefixed to their identifiers. If the items root were “/en/”
    # instead, an item at content/about.html would have an identifier of
    # “/en/about/” instead of just “/about/”.
    items_root: /

    # The path where layouts should be mounted. The layouts root behaves the
    # same as the items root, but applies to layouts rather than items.
    layouts_root: /

base_url: http://mildred.fr
site_name: Mildred's Website

deploy:
  default:
    dst: "mildred_mildredkilya@ssh.phx.nearlyfreespeech.net:/home/public"
    options: ["--rsh=ssh", '-glpPrtvz', '--del', '--delete-excluded', '--exclude=.hg', '--exclude=.git', '--exclude=.svn']

tags:
  page:    "/tags/%s/"
  content: "= render '_index_page'"
  title:   "Category: %s"
  attributes:
    filter: haml
    layout: default
    page_size: 10

author:
  Mildred: "http://mildred.fr"

# Atom feed

author_name:   Mildred Ki'Lya
author_uri:    http://mildred.fr


